[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# Отключаем хелсчеки для Railway
healthcheck = false
startCommand = "node express-server.js"
restartPolicyType = "no"
numReplicas = 1

# Добавляем секцию для указания Docker
[container]
expose = 3000 